language: ruby
notifications:
  email: false
rvm:
  - 2.1.1
env: DISPLAY=:99.0
before_script:
  - mysql -e 'create database leihs2_test;'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/database_travis.yml config/database.yml"
  - "rm -f tmp/*.mysql"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install imagemagick wget memcached phantomjs openjdk-7-jre"
bundler_args: --without development
cache: bundler
script:
  - bundle exec cucumber -t ~@browser
